name: hive_generator
description: Extension for Hive. Automatically generates TypeAdapters to store any class.
version: 0.7.0+2
homepage: https://github.com/hivedb/hive/tree/master/hive_generator
documentation: https://docs.hivedb.dev/

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  build: ^1.3.0
  source_gen: ^0.9.6
  hive: ">=1.3.0 <2.0.0"
  analyzer: ">=0.39.12"
  dartx: ^0.4.2

dependency_overrides:
  hive:
    path: ../hive

dev_dependencies:
  test: ^1.15.2
  build_test: 1.2.0
  build_runner: 1.10.0
  pedantic: "1.9.2"
